logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG

debug: true

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:49153/coroutine?schema=public
    username: postgres
    password: postgrespw
    properties:
      ssl: false