logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG

debug: true

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:49153/coroutine?schema=public
    username: postgres
    password: postgrespw
    properties:
      ssl: false
#      sslMode: REQUIRE
#    pool:
#      enabled: true
#      initial-size: 22
#      max-size: 30
#      max-idle-time: 5m
#      validation-query: SELECT 1